import { spotifyApiFetch } from './spotifyClient'
import type { SpotifyPlaylist } from './spotifyPlayback'

export interface SpotifyProfile {
  id: string
  displayName: string | null
}

export async function fetchSpotifyProfile(): Promise<{ ok: true; data: SpotifyProfile } | { ok: false; error: string }> {
  const result = await spotifyApiFetch('/me')
  if (!result.ok) return result
  if (!result.response.ok) return { ok: false, error: `Couldn't load your Spotify profile (${result.response.status})` }
  const json = (await result.response.json()) as { id: string; display_name: string | null }
  return { ok: true, data: { id: json.id, displayName: json.display_name } }
}

// Search terms standing in for Spotify's audio-feature-based recommendations (low energy,
// instrumental, steady tempo) — search against editorial/genre terms is the one track-discovery
// path still broadly available on the Web API, unlike /v1/recommendations.
const DEEP_WORK_SEARCH_QUERIES = ['deep focus', 'instrumental study', 'ambient focus', 'lo-fi beats', 'peaceful piano', 'focus flow']

const MAX_CANDIDATE_TRACKS = 40
const PLAYLIST_TRACK_COUNT = 30

interface RawSearchTrack {
  uri: string
}

async function collectCandidateTrackUris(): Promise<string[]> {
  const uris = new Set<string>()
  for (const query of DEEP_WORK_SEARCH_QUERIES) {
    if (uris.size >= MAX_CANDIDATE_TRACKS) break
    const result = await spotifyApiFetch(`/search?q=${encodeURIComponent(query)}&type=track&limit=12`)
    if (!result.ok || !result.response.ok) continue
    const json = (await result.response.json()) as { tracks?: { items?: RawSearchTrack[] } }
    for (const track of json.tracks?.items ?? []) uris.add(track.uri)
  }
  return Array.from(uris)
}

/** Creates a new private playlist in the user's own Spotify account, seeded from a handful of
 *  focus-oriented search terms, and returns it in the same shape as fetchUserPlaylists() so it
 *  drops straight into the Focus Music profile pickers. */
export async function generateDeepWorkPlaylist(
  name: string,
): Promise<{ ok: true; data: SpotifyPlaylist } | { ok: false; error: string }> {
  const profileResult = await fetchSpotifyProfile()
  if (!profileResult.ok) return profileResult

  const candidateUris = await collectCandidateTrackUris()
  if (candidateUris.length === 0) return { ok: false, error: "Couldn't find any tracks — try again shortly" }
  const trackUris = candidateUris.sort(() => Math.random() - 0.5).slice(0, PLAYLIST_TRACK_COUNT)

  const createResult = await spotifyApiFetch(`/users/${profileResult.data.id}/playlists`, {
    method: 'POST',
    body: JSON.stringify({
      name,
      public: false,
      description: 'Generated by Goals Tracker for deep work sessions.',
    }),
  })
  if (!createResult.ok) return createResult
  if (!createResult.response.ok) return { ok: false, error: `Couldn't create the playlist (${createResult.response.status})` }
  const playlist = (await createResult.response.json()) as { id: string; name: string; uri: string }

  const addResult = await spotifyApiFetch(`/playlists/${playlist.id}/tracks`, {
    method: 'POST',
    body: JSON.stringify({ uris: trackUris }),
  })
  if (!addResult.ok || !addResult.response.ok) {
    return { ok: false, error: 'Playlist created, but adding tracks failed — try generating again' }
  }

  return {
    ok: true,
    data: { id: playlist.id, name: playlist.name, uri: playlist.uri, imageUrl: null, trackCount: trackUris.length },
  }
}
